detection/examples/PythonOcvComponent/ocv_component/__init__.py, detection/examples/PythonOcvComponent/ocv_component/ocv_component.py, detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonOcvComponent/setup.py, detection/examples/PythonTestComponent/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/3)
=> Add example Python component that uses setuptools and OpenCV

README.md, detection/api/mpf_component_api/mpf_component_api.py, detection/api/mpf_component_api/mpf_component_api_util.py, detection/component_util/mpf_component_util/frame_filters/frame_filter.py, detection/component_util/mpf_component_util/frame_filters/frame_list_filters.py, detection/component_util/mpf_component_util/frame_filters/interval_frame_filter.py, detection/component_util/mpf_component_util/frame_filters/seek_strategies.py, detection/component_util/mpf_component_util/frame_transformers/frame_cropper.py, detection/component_util/mpf_component_util/frame_transformers/frame_flipper.py, detection/component_util/mpf_component_util/frame_transformers/frame_rotator.py, detection/component_util/mpf_component_util/frame_transformers/frame_transformer.py, detection/component_util/mpf_component_util/frame_transformers/frame_transformer_factory.py, detection/component_util/mpf_component_util/image_reader.py, detection/component_util/mpf_component_util/utils.py, detection/component_util/mpf_component_util/video_capture.py, detection/component_util/tests/__main__.py, detection/component_util/tests/test_image_reader.py, detection/component_util/tests/test_rect.py, detection/component_util/tests/test_util.py, detection/component_util/tests/test_video_capture.py, detection/examples/PythonOcvComponent/ocv_component/ocv_component.py, detection/examples/PythonTestComponent/test_component.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/6)
=> Python __future__ imports

detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonTestComponent/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/7)
=> Updated version to 2.1.0.

detection/component_util/mpf_component_util/__init__.py, detection/component_util/mpf_component_util/models_ini_parser.py, detection/component_util/tests/test_models_ini_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/8)
=> Add Python version of ModelsIniParser

detection/component_util/mpf_component_util/image_reader.py, detection/component_util/mpf_component_util/video_capture.py, detection/component_util/setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/11)
=> Modify mpf_component_util.ImageReader to ues cv2.VideoCapture instead of cv2.imread.

detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonTestComponent/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/13)
=> Updated version to 3.0.0.

detection/component_util/mpf_component_util/__init__.py, detection/component_util/mpf_component_util/audio_ripper.py, detection/component_util/mpf_component_util/mpf_audio_detection_media_handler.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/15)
=> Video handling

detection/component_util/mpf_component_util/frame_transformers/frame_transformer_factory.py, detection/component_util/tests/test_image_reader.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/16)
=> Allow percentages in search region properties

detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonTestComponent/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/18)
=> Update version to 4.1.0.

detection/component_util/mpf_component_util/__init__.py, detection/component_util/mpf_component_util/models_ini_parser.py, detection/component_util/tests/test_models_ini_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/21)
=> Add optional field to ModelsIniParser

detection/component_util/mpf_component_util/audio_transcoder.py, detection/component_util/mpf_component_util/frame_filters/frame_list_filters.py, detection/component_util/mpf_component_util/video_capture.py
Resolves: https://github.com/openmpf/openmpf/issues/1173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/28)
=> Fix exception handling in audio_transcoder.py and frame_list_filters.py.

detection/component_util/mpf_component_util/audio_transcoder.py, detection/component_util/mpf_component_util/frame_filters/frame_list_filters.py, detection/component_util/mpf_component_util/video_capture.py
Merges https://github.com/openmpf/openmpf-python-component-sdk/pull/28 in to develop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/29)
=> Fix exception handling in audio_transcoder.py and frame_list_filters.py

detection/component_util/setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/30)
=> Limit max version of opencv-python to avoid build errors.

detection/component_util/mpf_component_util/frame_transformers/affine_frame_transformer.py, detection/component_util/mpf_component_util/frame_transformers/frame_transformer_factory.py, detection/component_util/mpf_component_util/utils.py, detection/component_util/tests/test_affine_transformer.py
Resolves https://github.com/openmpf/openmpf/issues/1194
Resolves https://github.com/openmpf/openmpf/issues/1196
- https://github.com/openmpf/openmpf/pull/1195
- https://github.com/openmpf/openmpf-components/pull/203
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/93
- https://github.com/openmpf/openmpf-python-component-sdk/pull/33
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/33)
=> Add support for ROTATION_THRESHOLD and ROTATION_FILL_COLOR

detection/component_util/setup.py
- https://github.com/openmpf/openmpf/pull/1136
- https://github.com/openmpf/openmpf-docker/pull/108
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/89
- https://github.com/openmpf/openmpf-python-component-sdk/pull/37
- https://github.com/openmpf/openmpf-components/pull/174
- https://github.com/openmpf/openmpf-contrib-components/pull/63
Issues:
- https://github.com/openmpf/openmpf/issues/1101
- https://github.com/openmpf/openmpf/issues/1073
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/37)
=> Upgrade to OpenCV4

detection/api/setup.py, detection/component_util/setup.py, detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonOcvComponent/setup.py, detection/examples/PythonTestComponent/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/38)
=> Update versions to 6.0.

detection/component_util/mpf_component_util/__init__.py, detection/component_util/mpf_component_util/http_retry.py, detection/component_util/tests/test_http_retry.py
Issue: https://github.com/openmpf/openmpf/issues/1270
- https://github.com/openmpf/openmpf/pull/1276
- https://github.com/openmpf/openmpf-components/pull/237
- https://github.com/openmpf/openmpf-python-component-sdk/pull/41
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/41)
=> Add HttpRetry

detection/component_util/mpf_component_util/__init__.py, detection/component_util/mpf_component_util/http_retry.py, detection/component_util/tests/test_http_retry.py
Merges: https://github.com/openmpf/openmpf-python-component-sdk/pull/41
- https://github.com/openmpf/openmpf/pull/1277
- https://github.com/openmpf/openmpf-python-component-sdk/pull/42
- https://github.com/openmpf/openmpf-components/pull/238
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/42)
=> Add HttpRetry (#41)

detection/api/setup.py, detection/component_util/setup.py, detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonOcvComponent/setup.py, detection/examples/PythonTestComponent/descriptor/descriptor.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/43)
=> Update versions to 6.1.

detection/component_util/mpf_component_util/audio_transcoder.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/44)
=> Make pass filtering configurable

detection/component_util/mpf_component_util/frame_filters/__init__.py, detection/component_util/mpf_component_util/frame_filters/seek_strategies.py, detection/component_util/mpf_component_util/video_capture.py, detection/component_util/tests/test_video_capture.py
Resolves: openmpf/openmpf#1307
- https://github.com/openmpf/openmpf/pull/1310
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/102
- https://github.com/openmpf/openmpf-python-component-sdk/pull/45
- https://github.com/openmpf/openmpf-docker/pull/141
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/45)
=> Support VFR videos

detection/component_util/mpf_component_util/frame_filters/__init__.py, detection/component_util/mpf_component_util/frame_filters/seek_strategies.py, detection/component_util/mpf_component_util/video_capture.py, detection/component_util/tests/test_video_capture.py
Merges https://github.com/openmpf/openmpf-python-component-sdk/pull/45 in to develop
Issue: https://github.com/openmpf/openmpf/issues/1307
- https://github.com/openmpf/openmpf/pull/1314
- https://github.com/openmpf/openmpf-python-component-sdk/pull/47
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/104
- https://github.com/openmpf/openmpf-docker/pull/143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/47)
=> Support VFR videos (#45)

detection/api/setup.py, detection/component_util/setup.py, detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonOcvComponent/setup.py, detection/examples/PythonTestComponent/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1322
- https://github.com/openmpf/openmpf/pull/1321
- https://github.com/openmpf/openmpf-components/pull/253
- https://github.com/openmpf/openmpf-contrib-components/pull/72
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/106
- https://github.com/openmpf/openmpf-python-component-sdk/pull/49
- https://github.com/openmpf/openmpf-java-component-sdk/pull/53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/49)
=> Update versions to 6.2.

detection/component_util/mpf_component_util/models_ini_parser.py, detection/component_util/tests/test_models_ini_parser.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/52)
=> Use proper error codes for ModelsIniError subclasses

detection/component_util/mpf_component_util/models_ini_parser.py, detection/component_util/tests/test_models_ini_parser.py
Merges: https://github.com/openmpf/openmpf-python-component-sdk/pull/52
**Issues:**
- https://github.com/openmpf/openmpf/issues/1330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/53)
=> Use proper error codes for ModelsIniError subclasses (#52)

detection/component_util/mpf_component_util/frame_transformers/frame_cropper.py, detection/component_util/tests/test_affine_transformer.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1386
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/54)
=> Fix negative coordinate handling in FeedForwardFrameCropper.

detection/component_util/mpf_component_util/frame_transformers/frame_cropper.py, detection/component_util/tests/test_affine_transformer.py
Merges: https://github.com/openmpf/openmpf-python-component-sdk/pull/54
**Issues:**
- https://github.com/openmpf/openmpf/issues/1386
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/55)
=> Merge: Fix negative coordinate handling in FeedForwardFrameCropper. (#54)

detection/api/setup.py, detection/component_util/setup.py, detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonOcvComponent/setup.py, detection/examples/PythonTestComponent/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1401
- https://github.com/openmpf/openmpf/pull/1400
- https://github.com/openmpf/openmpf-components/pull/279
- https://github.com/openmpf/openmpf-contrib-components/pull/75
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/107
- https://github.com/openmpf/openmpf-python-component-sdk/pull/56
- https://github.com/openmpf/openmpf-java-component-sdk/pull/54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/56)
=> Update versions to 6.3.

detection/component_util/mpf_component_util/image_reader.py, detection/component_util/mpf_component_util/video_capture.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1501
- https://github.com/openmpf/openmpf/pull/1508
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/61)
=> Hf merge/video rotation

detection/component_util/mpf_component_util/frame_transformers/frame_transformer_factory.py, detection/component_util/tests/test_affine_transformer.py, detection/component_util/tests/test_util.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1566
- https://github.com/openmpf/openmpf/pull/1576
- https://github.com/openmpf/openmpf-components/pull/304
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/117
- https://github.com/openmpf/openmpf-python-component-sdk/pull/66
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/66)
=> Make auto orientation true by default.

detection/api/setup.cfg, detection/component_util/setup.cfg, detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonOcvComponent/setup.cfg, detection/examples/PythonTestComponent/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1634
- https://github.com/openmpf/openmpf/pull/1633
- https://github.com/openmpf/openmpf-components/pull/314
- https://github.com/openmpf/openmpf-contrib-components/pull/85
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/118
- https://github.com/openmpf/openmpf-java-component-sdk/pull/60
- https://github.com/openmpf/openmpf-python-component-sdk/pull/70
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/70)
=> Update versions to 7.1.

detection/component_util/mpf_component_util/job_config.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1643
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/72)
=> Remove logic for overwriting speaker IDs

detection/api/setup.cfg, detection/component_util/setup.cfg, detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonOcvComponent/setup.cfg, detection/examples/PythonTestComponent/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1683
- https://github.com/openmpf/openmpf/pull/1682
- https://github.com/openmpf/openmpf-components/pull/330
- https://github.com/openmpf/openmpf-contrib-components/pull/87
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/120
- https://github.com/openmpf/openmpf-java-component-sdk/pull/62
- https://github.com/openmpf/openmpf-python-component-sdk/pull/75
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/75)
=> Update versions to 7.2.

detection/api/setup.cfg, detection/component_util/setup.cfg, detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonOcvComponent/setup.cfg, detection/examples/PythonTestComponent/descriptor/descriptor.json
**Issues:**
- https://github.com/openmpf/openmpf/issues/1737
- https://github.com/openmpf/openmpf.github.io/pull/173
- https://github.com/openmpf/openmpf/pull/1738
- https://github.com/openmpf/openmpf-components/pull/345
- https://github.com/openmpf/openmpf-contrib-components/pull/89
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/122
- https://github.com/openmpf/openmpf-java-component-sdk/pull/64
- https://github.com/openmpf/openmpf-python-component-sdk/pull/76
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/76)
=> Update version numbers to 8.0.

detection/api/setup.cfg, detection/component_util/setup.cfg, detection/examples/PythonOcvComponent/plugin-files/descriptor/descriptor.json, detection/examples/PythonOcvComponent/setup.cfg, detection/examples/PythonTestComponent/descriptor/descriptor.json, detection/nlp_text_splitter/pyproject.toml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1801
- https://github.com/openmpf/openmpf/pull/1802
- https://github.com/openmpf/openmpf-components/pull/367
- https://github.com/openmpf/openmpf-contrib-components/pull/91
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/125
- https://github.com/openmpf/openmpf-python-component-sdk/pull/79
- https://github.com/openmpf/openmpf-java-component-sdk/pull/65
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/79)
=> Update version numbers to 9.0.

detection/nlp_text_splitter/pyproject.toml
Merges: https://github.com/openmpf/openmpf-python-component-sdk/pull/82
**Issues:**
- https://github.com/openmpf/openmpf/issues/1827
resolves openmpf/openmpf#1827
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/83)
=> Hf merge/thinc version

detection/nlp_text_splitter/pyproject.toml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1842
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/85)
=> Restrict version of spacy

detection/nlp_text_splitter/pyproject.toml
Merges: https://github.com/openmpf/openmpf-python-component-sdk/pull/85
**Issues:**
- https://github.com/openmpf/openmpf/issues/1842
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/86)
=> Hf merge/spacy version

detection/nlp_text_splitter/README.md, detection/nlp_text_splitter/install.sh, detection/nlp_text_splitter/pyproject.toml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1859
- https://github.com/openmpf/openmpf-docker/pull/228
- https://github.com/openmpf/openmpf-components/pull/386
- https://github.com/openmpf/openmpf-python-component-sdk/pull/88
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/88)
=> Fix text splitter install script
